# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json
PackageIdentifier: DartPDF.DartPDF
PackageVersion: 7.0.0
PackageLocale: en-US
Publisher: DartPDF
PublisherUrl: https://dart-pdf.com/
PublisherSupportUrl: https://github.com/ben-milanko/dart-pdf/issues
PrivacyUrl: https://dart-pdf.com/privacy
Author: Ben Milanko
PackageName: DartPDF
PackageUrl: https://dart-pdf.com/
License: Apache-2.0
LicenseUrl: https://github.com/ben-milanko/dart-pdf/blob/app-v7.0.0/LICENSE
ShortDescription: Fill and sign PDF forms. Edit, annotate and redact on your Windows PC, without uploading your files.
Moniker: dartpdf
Tags:
  - annotate
  - forms
  - pdf
  - pdf-editor
  - redact
  - sign
Documentations:
  - DocumentLabel: Fill and sign a PDF with DartPDF
    DocumentUrl: https://github.com/ben-milanko/dart-pdf/blob/main/doc/guides/fill-and-sign-pdf.md
ReleaseNotesUrl: https://github.com/ben-milanko/dart-pdf/releases/tag/app-v7.0.0
ManifestType: defaultLocale
ManifestVersion: 1.10.0
